template: true
valuesFilePath: ./values.yml

resources:
  - name: testcron
    type: GitRepo
    configuration:
      path: bharath92/multibranch-pipelines
      gitProvider: github
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: testcron
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          {{ if contains "{{gitBranch}}" "main1" }}
          inputResources:
            - name: mb1
          {{ end }}
        execution:
          onExecute:
            {{range $i, $e := until 5}}
            - echo hi{{$i}}
            {{end}}
